### ISSUE TITLE
Style background as 100lvh, 100lvw for nicer styling with dynamic viewports (mobile Safari)

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#131]
This change keeps the background from resizing in a kind of stuttery way when Safari's tab bar retracts and causes the viewport to grow:

```css
body::before {
  /* ... */
  width: 100lvw;
  height: 100lvh;
}
```

I spent a while looking into Safari not actually *rendering* the background while it's beneath the bottom-aligned tab bar, but of course, no progress there. It might just be a Safari bug/quirk.
