### ISSUE TITLE
Multiple Releases

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#144]
Planning TBD, discussion *highly imminent* in Discord. Probably in current release milestone as it's related to #70 and the overall theme of album presentation.

**Comment by towerofnix** [comment]
Some early planning discussion, in the context of flashes & games:

> thanks both for commenting on flashes/games as a subset of multiple releases tho! that brings up questions about supporting multiple & completely custom "classes" of releases, which would vary depending on wiki
>
> a wiki which covers individual physical releases in minute detail might want an extra kind of release to represent that for example
>
> and generalizing flashes & games as another kind of release would be a good way to ensure those classes are sufficiently featureful for a wide variety of uses
>
> while also moving away from the pretty strict/hard-coded behavior of flashes & games (or rather the way we tie all those behaviors into one package that is always under the label "Flashes & Games"), allowing better customizability of similar sections for other wikis ex. the celeste one Niklink put together

([Context in Discord.](https://discord.com/channels/749042497610842152/779895315750715422/1080994444515483658))

**Comment by towerofnix** [comment]
Very experimental `Release` data format implemented in #146:

```yaml
elease: Homestuck Vol. 9-10 (with [S] Collide. and Act 7)
Directory: homestuck-vol-9-10-with-s-collide-and-act-7
Date: October 25, 2019
Has Track Art: false
Color: '#0088ff'
Track List:
  - Homestuck Vol. 9:
    - Color: '#f2a400'
    - 'track:crystalmethequins'
    - 'track:anbroids-v2'
    - 'track:trepidation'
    - 'track:firefly'
  - Homestuck Vol. 10:
    - Color: '#0088ff'
    - 'track:creata'
    - 'track:train'
    - 'track:of-gods-and-witches'
  - '[S] Collide.':
    - Color: '#cc3322'
    - 'track:creata-canon-edit'
    - 'track:oppa-toby-style'
    - 'track:eternity-served-cold-canon-edit'
    - 'track:heir-of-grief'
  - Act 7:
    - Color: '#c7ff34'
    - 'track:overture-canon-edit'
```
