### ISSUE TITLE
Inherit track name when Originally Released As is set

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#274]
Thanks to Makin for this suggestion - he followed up these syntaxes:

```yaml
Track: Showtime (Piano Refrain)
Directory: showtime-piano-refrain-vol-1-4
Originally Released As: track:showtime-piano-refrain
---
Track: Harlequin
Directory: harlequin-vol-1-4
Originally Released As: track:harlequin
```

```yaml
Track: Showtime (Piano Refrain)
Directory: showtime-piano-refrain-vol-1-4
Originally Released As: Showtime (Piano Refrain)
---
Track: Harlequin
Directory: harlequin-vol-1-4
Originally Released As: Harlequin
```

...with this syntax:

```yaml
Originally Released As: Showtime (Piano Refrain)
Directory: showtime-piano-refrain-vol-1-4
---
Originally Released As: Harlequin
Directory: harlequin-vol-1-4
```

Implementation notes:

* Shouldn't be too bad to implement with compositional style, waiting on #256. Awkward to implement with existing (pre/semi-compositional) utilities.
* YAML parser will need to be updated to accept `Originally Released As` as a valid "track identifier" just like `Track`. This is necessary since it distinguishes between tracks and track sections (in entry documents).
* Still allow setting (i.e. overriding with) own track name - re-releases aren't always named the same as the original track.
