### ISSUE TITLE
URL resolving should handle commonalities in arguments

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#333]
Okay, so here's an example bit of `transformContent`-processed text you might find in YAML:

```yaml
Track: Eternity Served Cold
Additional Names:
- Name: Eternity's Shylock
  Annotation: >-
    earlier MSPA credit, see also
    [[track:eternity-served-cold#artist-commentary|commentary]]
```

Cool cool. So the `[[track]]` link is good because this text could be rendered anywhere, but one place it'll *definitely* be rendered is the track page itself. With our current URL system, its href will be computed like this:

```
<a href="../eternity-served-cold/#artist-commentary">commentary</a>
```

That's because the `.from()` call only knows that it's going from *any* `localized.trackInfo`-specified path! It doesn't know we're going from `localized.trackInfo`-with-arg1-`eternity-served-cold`, so it can't make a smarter pathname decision based on that.

Now that's mostly by design - we don't want to recompute every goddang path after all. Creating a cache of "from any path key, to any path key" is [quite good for performance](https://hsmusic.wiki/changelog/#12-mar-2021).

But it *should* be possible to do both: to depend on a backing cache *and* internally track exactly which page you're coming from!

There are probably multiple ways to do this, but I want to support the above case (resolving to just `#artist-commentary`) *and* this less trivial one:

```yaml
urlSpec.localized.albumGallery:     "album/<>/gallery/"
urlSpec.localized.albumCommentary:  "album/<>/commentary/"

from: [localized.albumGallery,     one-year-older]
to:   [localized.albumCommentary,  one-year-older]

wouldBe:   "../../one-year-older/commentary/"
shouldBe:  "../commentary/"
```

I think the right algorithmic approach when caching paths is probably to...

1. Iteratively, for each argument *position* (not value! no values are accessible at this point), counting up in `n`, and starting in the position BEFORE the first matching argument (i.e. "zero matching arguments"):
2. Filter over keys for whose path, up to *its* argument position `n`, exactly matches the "from" key's path, up to argument position `n`.
  * Note: This filter will always include the "from" key!
  * The filter also, by definition, includes *all* keys, if `n` is the "zero matching arguments" position.
4. Compute relative paths between "from" and each of the filtered keys, *assuming that* the arguments, up to and including position `n`, are identical.
5. Push the mapping of these relative paths onto a "same argument" list (such that the mapping's index in that list is equal to `n`).

And then, when actually querying a path, assuming we're provided both `fromArgs` and `toArgs`:

1. Check how many arguments are common between `fromArgs` and `toArgs`, i.e. count up to the first argument which *doesn't* match.
2. Iteratively, counting *down*, with `n` being the position of the last matching argument:
3. Access the mapping, at position `n` in the "same argument" list (for this "from" key), and check if it has a value for the "to" key we're looking for.
4. If it does, slot the *remaining* arguments, i.e. everything *after* position `n`, into that value. By definition, the arguments up to and including `n` are already common, so only the remaining ones need to be slotted in. Then we're done, return this path!
6. If it doesn't, keep going, iterating down one.

A couple important things about this process:

* We're counting down and not only handling the specific case where the last argument matches - so, matching at least *some* of the arguments will still let you access whatever commonality goes up to that argument position, and the closest commonality is still matched first. It also allows for there being more keys in the mapping the fewer arguments are matched - so we're comparing more parts than just the suffix after the very last argument.
* This is still caching-friendly! It's definitely more work per path-to-path pairing (i.e. exponential), but once the cache is done, each URL should still compute with dramatically less work - i.e. growing in terms of number of arguments (linear, and comparatively very, very small).

It's also convenient that the querying process *doesn't* have a fallback case for after the "zero matching arguments" position - it reuses the exact same logic, because by definition, *that* mapping will include *all* keys. (Resting on the assumption that the provided "to" key is valid in the first place.) Defining the base case in the same terms/language as the later cases just makes it nicer to reason about overall. ("Zero matching arguments" is just another form of "N matching arguments", after all, and the domain of the process is by definition zero-to-length matching arguments.)
