### ISSUE TITLE
Unresolved "Originally Released Track" wreaks havoc

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#401]
See discussion from vriska ([#software-support](https://discord.com/channels/749042497610842152/1153707535895908584/1204177680858091561)).

```yaml
Track: Before the Story
Directory: before-the-story-undertale
Originally Released As: track:before-the-story
# But prior to this `track:before-the-story` having been added,
# so this resolved null.
```

A warning is correctly printed but come through anyway, instead of just treating the track as though it's an original.

```
[Errors validating between-thing references in data]
 ╿ [Reference errors in wikiData.trackData]
 │  ╿ [Reference errors in [rerelease] Track "Before the Story" (track:before-the-story-undertale) (#108 in UNDERTALE Soundtrack)]
 │  ╎  ╿ [Reference error in field Originally Released As]
 │  ╎  │  ╿ Didn't match anything for track:before-the-story
The above errors were detected while validating references in data files.
The wiki will still build, but these connections between data objects
will be completely skipped. Resolve the errors for more complete output.
```

This error occurred when loading any track page:

```
2/5/2024, 04:31:36 PM [500] /track/doctor/
Error computing composition reverseContributionList
 ↪ Error computing composition withReverseContributionList
    ↪ referenceList is not iterable
```

This is something we ran into today while editing Archive, and Morris did, too. It's a pretty high-impact bug when working with re-releases in data.
