### ISSUE TITLE
Contributions: Show credited-as name in artist tooltip

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#468]
Now that we have tooltips for artist links, we're thinking those could serve as an appropriate place to surface credited-as information in the user interface. Mock-up below:

<img width="419" alt="Tooltip for co-artist Eston Schweickart on track Bronze Page; the tooltip begins with slightly small, italicized, and plain-white text: Credited as: Eston 'silence' Schweickart. Then a dotted and colored divider line, and the usual icons and social handles." src="https://github.com/hsmusic/hsmusic-wiki/assets/9948030/09846cd0-9b54-4f29-a976-af5ba5a5f242">

This data needs to be entered separately from verbatim credits, which are pure content text and can't have meaning parsed in a totally general manner. (We could extract and apply a baseline automatically for review, though: hsmusic/bc-art#10.)

These are details on contributions, so the contribution format would be updated:

```yaml
# Expanded form
Artists:
- Artist: Ian White
  Credited: Ian "MyUsernamesMud" White
- Artist: Eston Schweickart
  Credited: Eston "silence" Schweickart
  Annotation: fake annotation
Contributors:
- Artist: Ally Clark
  Annotation: vocals

# Compact form
Artists:
- Ian White (as Ian "MyUsernamesMud" White)
- Eston Schweickart (fake annotation; as Eston "silence" Schweickart)
Contributors:
- Ally Clark (vocals)
# note the keyword `as` or `; as`
```

It would be *nice* to support entering multiple credited-as names, e.g.

```yaml
Artists:
- Artist: Toby Fox
  Credited: [Radiation, Toby "Radiation" Fox]
```

Particularly if an artist was credited under various names on different platforms/sources. The purpose of this interface is **not** to provide full crediting details; that's verbatim credits. So if we want to support multiple names, they probably should *not* each get a source accent. Mockup:

<img width="278" alt="The same tooltip as before, but with an additional line, reading: and: SiAsInSilence. This line is horizontally aligned so that the names appear in a column." src="https://github.com/hsmusic/hsmusic-wiki/assets/9948030/509a93a4-6504-4603-adf3-e97041f34736">

Will require some tweaks in CSS, mainly splitting the tooltip into two grid areas—the "credited as" / "name" columns should be aligned independently of the "icon" / "handle" / "platform" columns.

---

We should consider presentation on artist info pages as well—left as a stub/todo for the moment.

This issue is not directly related to "sub-artists", bands, etc, but it's part of a general area of thinking for representing contributions and credits on the wiki with more nuance.

Spiritually and practically, if not technically, pending on [verbatim credits](https://github.com/hsmusic/hsmusic-wiki/issues/432).

See [#hsmusic-chat](https://discord.com/channels/749042497610842152/779895315750715422/1231261501411557434) for discussion from Tangle and Makin.
