### ISSUE TITLE
Artist duplicate directory detection kinda broken?

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#497]
Given these artists...

```yaml
Artist: Doctor Chaos
---
Artist: Rom M
Aliases:
- Doctor Chaos
```

...you'd expect some kind of directory error, but none is showing up! Very strange.
