### ISSUE TITLE
Allow reusing another track's, album's, flash's etc artwork, in general!

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#545]
This is #231, but generalized for *all* kinds of artwork, in *all* contexts.

We're thinking to add a `Reuse From:` field, which can stand in place of normal artwork details. For example:

```yaml
# psycholonials-ep-1.yaml
Banner Artwork:
  Dimensions: 1100x180
  File Extension: png
  Contributors:
  - Andrew Hussie
  - Niklink (edits for wiki)

# psycholonials-ep-2.yaml
Banner Artwork:
  Reuse From: Psycholonials EP 1
```

This just exposes all the details from the referenced thing (which is always of the same type as the referencing thing, and always refers to the same field e.g. `Banner Artwork` above).

For now we don't need to worry about referencing one of *multiple* artworks (#70), but in the future this should be possible.

---

Obviously, this depends on extending artworks to be a proper object-shaped format (as above), for much easier access of relevant details (e.g. credits, file extension, dimension).

This also depends on those objects intrinsically exposing the "effective" location of the media file. If an artwork exposes a link back to its associated thing (as contributions do), then this should point to the reusing thing - not the reused thing - but we still need to know that this artwork's effective thing-directory is of the reused thing.

Generally, an artwork object created beause it was reused is not the same identity as the artwork on the reused item. It's a different object, in JavaScript terms. But the UI may wish to present reused artworks differently on occasion (e.g. special treatment in galleries); we should expose the presence of an original on a `reusedFrom` property. Artworks that *aren't* reused from somewhere else will expose `reusedFrom: null`.
