### ISSUE TITLE
Allow tracks to use a particular cover from the album

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#617]
Sort of a specialization for tracks as opposed (or in addition) to the very general #545, and obviously this follows up #70! 

See discussion in [#features-n-bugs](https://discord.com/channels/749042497610842152/1353745354708881479/1362356425728327791). Here's the example YAML rundown for the new field:

```yaml
Use Album Cover: none
# as opposed to null (sort of a special value)
# or false (implies it's a boolean - it isn't)

Use Album Cover: anime
# matches...
Album Cover:
- Label: Anime edition art
    # or whatever it's actually called LOL
  Directory: anime
    # THIS is what matches, as you say
    # so the label can be tweaked later
    # but the directory uniquely identifies it
    # for the sake of referencing above

# with no Use Album Cover specified, it just
# assumes you want to use the main cover art
```

We're expecting to be able to specify this probably both per track and per track section (the latter of which is a distinct behavior from #616, mind you).
