### ISSUE TITLE
Implement multiple artwork for tracks and albums

### ISSUE THREAD

**Issue by towerofnix** [hsmusic/hsmusic-wiki#70]
Lots of design sketches in Discord! A few highlights below for posterity also. (One tag per line idea included but we aren't going to use that one.)

![Screenshot from 2022-05-17 21-04-02](https://user-images.githubusercontent.com/9948030/172033018-bc4f9119-588f-44f7-9688-d2a6d8afc3cb.png)
![Screenshot from 2022-05-17 21-18-37](https://user-images.githubusercontent.com/9948030/172033020-5cf73d47-b1ad-4693-a52e-d40362b661a0.png)
![Screenshot from 2022-05-17 21-27-26](https://user-images.githubusercontent.com/9948030/172033023-4c6a753a-5506-4679-9092-44644782208b.png)
![Screenshot from 2022-05-17 21-27-30](https://user-images.githubusercontent.com/9948030/172033028-d64ae779-d451-4765-95cf-616d3dcc38b8.png)

(18 May 2022)

**Comment by towerofnix** [comment]
For data implementation, this will involve creating a wider field based off `Cover Artists` and related fields. Each artwork must be able to have its own artists, comment (description), and tags. The first will be displayed as the primary artwork, with the rest in equal, smaller dimensions beneath (maybe a *slightly* smaller font too).

Data sketch (not final):

```yaml
Artwork:
- Title: Anthology Artwork (2017)
  Image: psych0ruins.jpg
  # these can be expressed in expanded form ofc
  Artists: ['porrim-maryam']
  Tags: ['Aradia']
- Title: Original Artwork (2010)
  Image: psych0ruins-original.jpg
  Artists: ['Homestuck']
  Tags: ['Aradia']
```

Sketch notes:

- If the `Cover Artists` and `Art Tags` fields are present, they should be ported to the new format (without a `Title`). The original format should probably **not** be taken as deprecated/obsolete, at least for now.

- If `Image` is not provided, it should default to the usual value: `${track.directory}.jpg`.

- The new format makes `Cover Art File Extension` obsolete (except inasmuch as it's used to calculate the default if `Image` isn't provided).

(18 May 2022)
